--- 
user: root
group: root
chdir: /home/ubuntu/strozek
log: log/thin.log
environment: production
address: 0.0.0.0
port: 80
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
max_conns: 1024
require: []
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
